import 'package:json_annotation/json_annotation.dart';

import 'enums.dart';

@JsonEnum(fieldRename: FieldRename.snake)
enum EntityType { company, datacenter }

@JsonEnum(fieldRename: FieldRename.snake)
enum TransactionType { buy, sell }

@JsonEnum(fieldRename: FieldRename.snake)
enum Country {
  us(
    "US",
    "USA",
    "United States of America",
    true,
    1,
    AddressRegion.notClassified,
    "🇺🇸",
  ),
  ca("CA", "CAN", "Canada", true, 1, AddressRegion.notClassified, "🇨🇦"),
  af('AF', 'AFG', 'Afghanistan', false, 1, AddressRegion.southernAsia, "🇦🇫"),
  ax(
    'AX',
    'ALA',
    'Åland Islands',
    false,
    1,
    AddressRegion.westernEurope,
    "🇦🇽",
  ),
  al('AL', 'ALB', 'Albania', false, 1, AddressRegion.southernEurope, "🇦🇱"),
  dz('DZ', 'DZA', 'Algeria', false, 1, AddressRegion.northernAfrica, "🇩🇿"),
  as('AS', 'ASM', 'American Samoa', false, 1, AddressRegion.oceania, "🇦🇸"),
  ad('AD', 'AND', 'Andorra', false, 1, AddressRegion.southernEurope, "🇦🇩"),
  ao('AO', 'AGO', 'Angola', false, 1, AddressRegion.middleAfrica, "🇦🇴"),
  ai('AI', 'AIA', 'Anguilla', false, 1, AddressRegion.notClassified, "🇦🇮"),
  aq('AQ', 'ATA', 'Antarctica', false, 1, AddressRegion.notClassified, "🇦🇶"),
  ag(
    'AG',
    'ATG',
    'Antigua and Barbuda',
    false,
    1,
    AddressRegion.caribbean,
    "🇦🇬",
  ),
  ar('AR', 'ARG', 'Argentina', false, 1, AddressRegion.southAmerica, "🇦🇷"),
  am('AM', 'ARM', 'Armenia', false, 1, AddressRegion.westernAsia, "🇦🇲"),
  aw('AW', 'ABW', 'Aruba', false, 1, AddressRegion.caribbean, "🇦🇼"),
  au(
    'AU',
    'AUS',
    'Australia',
    false,
    1,
    AddressRegion.australiaNewZealand,
    "🇦🇺",
  ),
  at('AT', 'AUT', 'Austria', false, 1, AddressRegion.westernEurope, "🇦🇹"),
  az('AZ', 'AZE', 'Azerbaijan', false, 1, AddressRegion.westernAsia, "🇦🇿"),
  bs('BS', 'BHS', 'Bahamas (the)', false, 1, AddressRegion.caribbean, "🇧🇸"),
  bh('BH', 'BHR', 'Bahrain', false, 1, AddressRegion.westernAsia, "🇧🇭"),
  bd('BD', 'BGD', 'Bangladesh', false, 1, AddressRegion.southernAsia, "🇧🇩"),
  bb('BB', 'BRB', 'Barbados', false, 1, AddressRegion.caribbean, "🇧🇧"),
  by('BY', 'BLR', 'Belarus', false, 1, AddressRegion.easternEurope, "🇧🇾"),
  be('BE', 'BEL', 'Belgium', false, 1, AddressRegion.westernEurope, "🇧🇪"),
  bz('BZ', 'BLZ', 'Belize', false, 1, AddressRegion.centralAmerica, "🇧🇿"),
  bj('BJ', 'BEN', 'Benin', false, 1, AddressRegion.westernAfrica, "🇧🇯"),
  bm('BM', 'BMU', 'Bermuda', false, 1, AddressRegion.caribbean, "🇧🇲"),
  bt('BT', 'BTN', 'Bhutan', false, 1, AddressRegion.southernAsia, "🇧🇹"),
  bo(
    'BO',
    'BOL',
    'Bolivia (Plurinational State of)',
    false,
    1,
    AddressRegion.southAmerica,
    "🇧🇴",
  ),
  bq(
    'BQ',
    'BES',
    'Bonaire, Sint Eustatius and Saba',
    false,
    1,
    AddressRegion.caribbean,
    "🇧🇶",
  ),
  ba(
    'BA',
    'BIH',
    'Bosnia and Herzegovina',
    false,
    1,
    AddressRegion.southernEurope,
    "🇧🇦",
  ),
  bw('BW', 'BWA', 'Botswana', false, 1, AddressRegion.southernAfrica, "🇧🇼"),
  bv('BV', 'BVT', 'Bouvet Island', false, 1, AddressRegion.caribbean, "🇧🇻"),
  br('BR', 'BRA', 'Brazil', false, 1, AddressRegion.southAmerica, "🇧🇷"),
  io(
    'IO',
    'IOT',
    'British Indian Ocean Territory (the)',
    false,
    1,
    AddressRegion.southernAsia,
    "🇮🇴",
  ),
  bn(
    'BN',
    'BRN',
    'Brunei Darussalam',
    false,
    1,
    AddressRegion.southEasternAsia,
    "🇧🇳",
  ),
  bg('BG', 'BGR', 'Bulgaria', false, 1, AddressRegion.easternEurope, "🇧🇬"),
  bf(
    'BF',
    'BFA',
    'Burkina Faso',
    false,
    1,
    AddressRegion.westernAfrica,
    "🇧🇫",
  ),
  bi('BI', 'BDI', 'Burundi', false, 1, AddressRegion.easternAfrica, "🇧🇮"),
  cv('CV', 'CPV', 'Cabo Verde', false, 1, AddressRegion.westernAfrica, "🇨🇻"),
  kh('KH', 'KHM', 'Cambodia', false, 1, AddressRegion.southEasternAsia, "🇰🇭"),
  cm('CM', 'CMR', 'Cameroon', false, 1, AddressRegion.middleAfrica, "🇨🇲"),
  ky(
    'KY',
    'CYM',
    'Cayman Islands (the)',
    false,
    1,
    AddressRegion.caribbean,
    "🇰🇾",
  ),
  cf(
    'CF',
    'CAF',
    'Central African Republic (the)',
    false,
    1,
    AddressRegion.middleAfrica,
    "🇨🇫",
  ),
  td('TD', 'TCD', 'Chad', false, 1, AddressRegion.middleAfrica, "🇹🇩"),
  cl('CL', 'CHL', 'Chile', false, 1, AddressRegion.southAmerica, "🇨🇱"),
  cn('CN', 'CHN', 'China', false, 1, AddressRegion.easternAsia, "🇨🇳"),
  cx(
    'CX',
    'CXR',
    'Christmas Island',
    false,
    1,
    AddressRegion.australiaNewZealand,
    "🇨🇽",
  ),
  cc(
    'CC',
    'CCK',
    'Cocos (Keeling) Islands (the)',
    false,
    1,
    AddressRegion.caribbean,
    "🇨🇨",
  ),
  co('CO', 'COL', 'Colombia', false, 1, AddressRegion.southAmerica, "🇨🇴"),
  km(
    'KM',
    'COM',
    'Comoros (the)',
    false,
    1,
    AddressRegion.easternAfrica,
    "🇰🇲",
  ),
  cd(
    'CD',
    'COD',
    'Congo (the Democratic Republic of the)',
    false,
    1,
    AddressRegion.middleAfrica,
    "🇨🇩",
  ),
  cg('CG', 'COG', 'Congo (the)', false, 1, AddressRegion.middleAfrica, "🇨🇬"),
  ck(
    'CK',
    'COK',
    'Cook Islands (the)',
    false,
    1,
    AddressRegion.polynesia,
    "🇨🇰",
  ),
  cr('CR', 'CRI', 'Costa Rica', false, 1, AddressRegion.centralAmerica, "🇨🇷"),
  ci(
    'CI',
    'CIV',
    "Côte d'Ivoire",
    false,
    1,
    AddressRegion.westernAfrica,
    "🇨🇮",
  ),
  hr('HR', 'HRV', 'Croatia', false, 1, AddressRegion.southernEurope, "🇭🇷"),
  cu('CU', 'CUB', 'Cuba', false, 1, AddressRegion.caribbean, "🇨🇺"),
  cw('CW', 'CUW', 'Curaçao', false, 1, AddressRegion.caribbean, "🇨🇼"),
  cy('CY', 'CYP', 'Cyprus', false, 1, AddressRegion.westernAsia, "🇨🇾"),
  cz('CZ', 'CZE', 'Czechia', false, 1, AddressRegion.easternEurope, "🇨🇿"),
  dk('DK', 'DNK', 'Denmark', false, 1, AddressRegion.northernEurope, "🇩🇰"),
  dj('DJ', 'DJI', 'Djibouti', false, 1, AddressRegion.easternAfrica, "🇩🇯"),
  dm('DM', 'DMA', 'Dominica', false, 1, AddressRegion.caribbean, "🇩🇲"),
  domrep(
    'DO',
    'DOM',
    'Dominican Republic (the)',
    false,
    1,
    AddressRegion.caribbean,
    "🇩🇴",
  ),
  ec('EC', 'ECU', 'Ecuador', false, 1, AddressRegion.southAmerica, "🇪🇨"),
  eg('EG', 'EGY', 'Egypt', false, 1, AddressRegion.northernAfrica, "🇪🇬"),
  sv(
    'SV',
    'SLV',
    'El Salvador',
    false,
    1,
    AddressRegion.centralAmerica,
    "🇸🇻",
  ),
  gq(
    'GQ',
    'GNQ',
    'Equatorial Guinea',
    false,
    1,
    AddressRegion.middleAfrica,
    "🇬🇶",
  ),
  er('ER', 'ERI', 'Eritrea', false, 1, AddressRegion.easternAfrica, "🇪🇷"),
  ee('EE', 'EST', 'Estonia', false, 1, AddressRegion.northernEurope, "🇪🇪"),
  sz('SZ', 'SWZ', 'Eswatini', false, 1, AddressRegion.southernAfrica, "🇸🇿"),
  et('ET', 'ETH', 'Ethiopia', false, 1, AddressRegion.easternAfrica, "🇪🇹"),
  fk(
    'FK',
    'FLK',
    'Falkland Islands (the) [Malvinas]',
    false,
    1,
    AddressRegion.southAmerica,
    "🇫🇰",
  ),
  fo(
    'FO',
    'FRO',
    'Faroe Islands (the)',
    false,
    1,
    AddressRegion.northernEurope,
    "🇫🇴",
  ),
  fj('FJ', 'FJI', 'Fiji', false, 1, AddressRegion.melanesia, "🇫🇯"),
  fi('FI', 'FIN', 'Finland', false, 1, AddressRegion.northernEurope, "🇫🇮"),
  fr('FR', 'FRA', 'France', false, 1, AddressRegion.westernEurope, "🇫🇷"),
  gf(
    'GF',
    'GUF',
    'French Guiana',
    false,
    1,
    AddressRegion.southAmerica,
    "🇬🇫",
  ),
  pf('PF', 'PYF', 'French Polynesia', false, 1, AddressRegion.oceania, "🇵🇫"),
  tf(
    'TF',
    'ATF',
    'French Southern Territories (the)',
    false,
    1,
    AddressRegion.oceania,
    "🇹🇫",
  ),
  ga('GA', 'GAB', 'Gabon', false, 1, AddressRegion.middleAfrica, "🇬🇦"),
  gm(
    'GM',
    'GMB',
    'Gambia (the)',
    false,
    1,
    AddressRegion.westernAfrica,
    "🇬🇲",
  ),
  ge('GE', 'GEO', 'Georgia', false, 1, AddressRegion.westernAsia, "🇬🇪"),
  de('DE', 'DEU', 'Germany', false, 1, AddressRegion.westernEurope, "🇩🇪"),
  gh('GH', 'GHA', 'Ghana', false, 1, AddressRegion.westernAfrica, "🇬🇭"),
  gi('GI', 'GIB', 'Gibraltar', false, 1, AddressRegion.southernEurope, "🇬🇮"),
  gr('GR', 'GRC', 'Greece', false, 1, AddressRegion.southernEurope, "🇬🇷"),
  gl('GL', 'GRL', 'Greenland', false, 1, AddressRegion.northernEurope, "🇬🇱"),
  gd('GD', 'GRD', 'Grenada', false, 1, AddressRegion.caribbean, "🇬🇩"),
  gp('GP', 'GLP', 'Guadeloupe', false, 1, AddressRegion.caribbean, "🇬🇵"),
  gu('GU', 'GUM', 'Guam', false, 1, AddressRegion.oceania, "🇬🇺"),
  gt('GT', 'GTM', 'Guatemala', false, 1, AddressRegion.centralAmerica, "🇬🇹"),
  gg('GG', 'GGY', 'Guernsey', false, 1, AddressRegion.westernEurope, "🇬🇬"),
  gn('GN', 'GIN', 'Guinea', false, 1, AddressRegion.westernAfrica, "🇬🇳"),
  gw(
    'GW',
    'GNB',
    'Guinea-Bissau',
    false,
    1,
    AddressRegion.westernAfrica,
    "🇬🇼",
  ),
  gy('GY', 'GUY', 'Guyana', false, 1, AddressRegion.southAmerica, "🇬🇾"),
  ht('HT', 'HTI', 'Haiti', false, 1, AddressRegion.caribbean, "🇭🇹"),
  hm(
    'HM',
    'HMD',
    'Heard Island and McDonald Islands',
    false,
    1,
    AddressRegion.southernAsia,
    "🇭🇲",
  ),
  va(
    'VA',
    'VAT',
    'Holy See (the)',
    false,
    1,
    AddressRegion.southernEurope,
    "🇻🇦",
  ),
  hn('HN', 'HND', 'Honduras', false, 1, AddressRegion.centralAmerica, "🇭🇳"),
  hk('HK', 'HKG', 'Hong Kong', false, 1, AddressRegion.easternAsia, "🇭🇰"),
  hu('HU', 'HUN', 'Hungary', false, 1, AddressRegion.easternEurope, "🇭🇺"),
  iceland(
    'IS',
    'ISL',
    'Iceland',
    false,
    1,
    AddressRegion.northernEurope,
    "🇮🇸",
  ),
  india('IN', 'IND', 'India', false, 1, AddressRegion.southernAsia, "🇮🇳"),
  id(
    'ID',
    'IDN',
    'Indonesia',
    false,
    1,
    AddressRegion.southEasternAsia,
    "🇮🇩",
  ),
  ir(
    'IR',
    'IRN',
    'Iran (Islamic Republic of)',
    false,
    1,
    AddressRegion.southernAsia,
    "🇮🇷",
  ),
  iq('IQ', 'IRQ', 'Iraq', false, 1, AddressRegion.westernAsia, "🇮🇶"),
  ie('IE', 'IRL', 'Ireland', false, 1, AddressRegion.northernEurope, "🇮🇪"),
  im(
    'IM',
    'IMN',
    'Isle of Man',
    false,
    1,
    AddressRegion.northernEurope,
    "🇮🇲",
  ),
  il('IL', 'ISR', 'Israel', false, 1, AddressRegion.westernAsia, "🇮🇱"),
  it('IT', 'ITA', 'Italy', false, 1, AddressRegion.southernEurope, "🇮🇹"),
  jm('JM', 'JAM', 'Jamaica', false, 1, AddressRegion.caribbean, "🇯🇲"),
  jp('JP', 'JPN', 'Japan', false, 1, AddressRegion.easternAsia, "🇯🇵"),
  je('JE', 'JEY', 'Jersey', false, 1, AddressRegion.northernEurope, "🇯🇪"),
  jo('JO', 'JOR', 'Jordan', false, 1, AddressRegion.westernAsia, "🇯🇴"),
  kz('KZ', 'KAZ', 'Kazakhstan', false, 1, AddressRegion.centralAsia, "🇰🇿"),
  ke('KE', 'KEN', 'Kenya', false, 1, AddressRegion.easternAfrica, "🇰🇪"),
  ki('KI', 'KIR', 'Kiribati', false, 1, AddressRegion.micronesia, "🇰🇮"),
  kp(
    'KP',
    'PRK',
    "Korea (the Democratic People's Republic of)",
    false,
    1,
    AddressRegion.easternAsia,
    "🇰🇵",
  ),
  kr(
    'KR',
    'KOR',
    'Korea (the Republic of)',
    false,
    1,
    AddressRegion.easternAsia,
    "🇰🇷",
  ),
  kw('KW', 'KWT', 'Kuwait', false, 1, AddressRegion.westernAsia, "🇰🇼"),
  kg('KG', 'KGZ', 'Kyrgyzstan', false, 1, AddressRegion.centralAsia, "🇰🇬"),
  la(
    'LA',
    'LAO',
    "Lao People's Democratic Republic (the)",
    false,
    1,
    AddressRegion.southEasternAsia,
    "🇱🇦",
  ),
  lv('LV', 'LVA', 'Latvia', false, 1, AddressRegion.northernEurope, "🇱🇻"),
  lb('LB', 'LBN', 'Lebanon', false, 1, AddressRegion.westernAsia, "🇱🇧"),
  ls('LS', 'LSO', 'Lesotho', false, 1, AddressRegion.southernAfrica, "🇱🇸"),
  lr('LR', 'LBR', 'Liberia', false, 1, AddressRegion.westernAfrica, "🇱🇷"),
  ly('LY', 'LBY', 'Libya', false, 1, AddressRegion.northernAfrica, "🇱🇾"),
  li(
    'LI',
    'LIE',
    'Liechtenstein',
    false,
    1,
    AddressRegion.westernEurope,
    "🇱🇮",
  ),
  lt('LT', 'LTU', 'Lithuania', false, 1, AddressRegion.northernEurope, "🇱🇹"),
  lu('LU', 'LUX', 'Luxembourg', false, 1, AddressRegion.westernEurope, "🇱🇺"),
  mo('MO', 'MAC', 'Macao', false, 1, AddressRegion.easternAsia, "🇲🇴"),
  mg('MG', 'MDG', 'Madagascar', false, 1, AddressRegion.easternAfrica, "🇲🇬"),
  mw('MW', 'MWI', 'Malawi', false, 1, AddressRegion.easternAfrica, "🇲🇼"),
  my('MY', 'MYS', 'Malaysia', false, 1, AddressRegion.southEasternAsia, "🇲🇾"),
  mv('MV', 'MDV', 'Maldives', false, 1, AddressRegion.southernAsia, "🇲🇻"),
  ml('ML', 'MLI', 'Mali', false, 1, AddressRegion.westernAfrica, "🇲🇱"),
  mt('MT', 'MLT', 'Malta', false, 1, AddressRegion.southernEurope, "🇲🇹"),
  mh(
    'MH',
    'MHL',
    'Marshall Islands (the)',
    false,
    1,
    AddressRegion.micronesia,
    "🇲🇭",
  ),
  mq('MQ', 'MTQ', 'Martinique', false, 1, AddressRegion.caribbean, "🇲🇶"),
  mr('MR', 'MRT', 'Mauritania', false, 1, AddressRegion.westernAfrica, "🇲🇷"),
  mu('MU', 'MUS', 'Mauritius', false, 1, AddressRegion.easternAfrica, "🇲🇺"),
  yt('YT', 'MYT', 'Mayotte', false, 1, AddressRegion.easternAfrica, "🇾🇹"),
  mx('MX', 'MEX', 'Mexico', false, 1, AddressRegion.centralAmerica, "🇲🇽"),
  fm(
    'FM',
    'FSM',
    'Micronesia (Federated States of)',
    false,
    1,
    AddressRegion.micronesia,
    "🇫🇲",
  ),
  md(
    'MD',
    'MDA',
    'Moldova (the Republic of)',
    false,
    1,
    AddressRegion.easternEurope,
    "🇲🇩",
  ),
  mc('MC', 'MCO', 'Monaco', false, 1, AddressRegion.westernEurope, "🇲🇨"),
  mn('MN', 'MNG', 'Mongolia', false, 1, AddressRegion.easternAsia, "🇲🇳"),
  me('ME', 'MNE', 'Montenegro', false, 1, AddressRegion.southernEurope, "🇲🇪"),
  ms('MS', 'MSR', 'Montserrat', false, 1, AddressRegion.notClassified, "🇲🇸"),
  ma('MA', 'MAR', 'Morocco', false, 1, AddressRegion.northernAfrica, "🇲🇦"),
  mz('MZ', 'MOZ', 'Mozambique', false, 1, AddressRegion.easternAfrica, "🇲🇿"),
  mm('MM', 'MMR', 'Myanmar', false, 1, AddressRegion.southEasternAsia, "🇲🇲"),
  na('NA', 'NAM', 'Namibia', false, 1, AddressRegion.southernAfrica, "🇳🇦"),
  nr('NR', 'NRU', 'Nauru', false, 1, AddressRegion.micronesia, "🇳🇷"),
  np('NP', 'NPL', 'Nepal', false, 1, AddressRegion.southernAsia, "🇳🇵"),
  nl(
    'NL',
    'NLD',
    'Netherlands (the)',
    false,
    1,
    AddressRegion.westernEurope,
    "🇳🇱",
  ),
  nc('NC', 'NCL', 'New Caledonia', false, 1, AddressRegion.oceania, "🇳🇨"),
  nz(
    'NZ',
    'NZL',
    'New Zealand',
    false,
    1,
    AddressRegion.australiaNewZealand,
    "🇳🇿",
  ),
  ni('NI', 'NIC', 'Nicaragua', false, 1, AddressRegion.centralAmerica, "🇳🇮"),
  ne('NE', 'NER', 'Niger (the)', false, 1, AddressRegion.westernAfrica, "🇳🇪"),
  ng('NG', 'NGA', 'Nigeria', false, 1, AddressRegion.westernAfrica, "🇳🇬"),
  nu('NU', 'NIU', 'Niue', false, 1, AddressRegion.polynesia, "🇳🇺"),
  nf('NF', 'NFK', 'Norfolk Island', false, 1, AddressRegion.oceania, "🇳🇫"),
  mp(
    'MP',
    'MNP',
    'Northern Mariana Islands (the)',
    false,
    1,
    AddressRegion.oceania,
    "🇲🇵",
  ),
  no('NO', 'NOR', 'Norway', false, 1, AddressRegion.northernEurope, "🇳🇴"),
  om('OM', 'OMN', 'Oman', false, 1, AddressRegion.westernAsia, "🇴🇲"),
  pw('PW', 'PLW', 'Palau', false, 1, AddressRegion.micronesia, "🇵🇼"),
  pk('PK', 'PAK', 'Pakistan', false, 1, AddressRegion.southernAsia, "🇵🇰"),
  ps(
    'PS',
    'PSE',
    'Palestine, State of',
    false,
    1,
    AddressRegion.westernAsia,
    "🇵🇸",
  ),
  pa('PA', 'PAN', 'Panama', false, 1, AddressRegion.centralAmerica, "🇵🇦"),
  pg(
    'PG',
    'PNG',
    'Papua New Guinea',
    false,
    1,
    AddressRegion.melanesia,
    "🇵🇬",
  ),
  py('PY', 'PRY', 'Paraguay', false, 1, AddressRegion.southAmerica, "🇵🇾"),
  pe('PE', 'PER', 'Peru', false, 1, AddressRegion.southAmerica, "🇵🇪"),
  ph(
    'PH',
    'PHL',
    'Philippines (the)',
    false,
    1,
    AddressRegion.southEasternAsia,
    "🇵🇭",
  ),
  pn('PN', 'PCN', 'Pitcairn', false, 1, AddressRegion.oceania, "🇵🇳"),
  pl('PL', 'POL', 'Poland', false, 1, AddressRegion.easternEurope, "🇵🇱"),
  pt('PT', 'PRT', 'Portugal', false, 1, AddressRegion.southernEurope, "🇵🇹"),
  pr('PR', 'PRI', 'Puerto Rico', false, 1, AddressRegion.caribbean, "🇵🇷"),
  qa('QA', 'QAT', 'Qatar', false, 1, AddressRegion.westernAsia, "🇶🇦"),
  mk(
    'MK',
    'MKD',
    'Republic of North Macedonia',
    false,
    1,
    AddressRegion.southernEurope,
    "🇲🇰",
  ),
  re('RE', 'REU', 'Réunion', false, 1, AddressRegion.easternAfrica, "🇷🇪"),
  ro('RO', 'ROU', 'Romania', false, 1, AddressRegion.easternEurope, "🇷🇴"),
  ru(
    'RU',
    'RUS',
    'Russian Federation (the)',
    false,
    1,
    AddressRegion.easternEurope,
    "🇷🇺",
  ),
  rw('RW', 'RWA', 'Rwanda', false, 1, AddressRegion.easternAfrica, "🇷🇼"),
  bl(
    'BL',
    'BLM',
    'Saint Barthélemy',
    false,
    1,
    AddressRegion.caribbean,
    "🇧🇱",
  ),
  sh(
    'SH',
    'SHN',
    'Saint Helena, Ascension and Tristan da Cunha',
    false,
    1,
    AddressRegion.westernAfrica,
    "🇸🇭",
  ),
  kn(
    'KN',
    'KNA',
    'Saint Kitts and Nevis',
    false,
    1,
    AddressRegion.caribbean,
    "🇰🇳",
  ),
  lc('LC', 'LCA', 'Saint Lucia', false, 1, AddressRegion.caribbean, "🇱🇨"),
  mf(
    'MF',
    'MAF',
    'Saint Martin (French part)',
    false,
    1,
    AddressRegion.caribbean,
    "🇲🇫",
  ),
  pm(
    'PM',
    'SPM',
    'Saint Pierre and Miquelon',
    false,
    1,
    AddressRegion.caribbean,
    "🇵🇲",
  ),
  vc(
    'VC',
    'VCT',
    'Saint Vincent and the Grenadines',
    false,
    1,
    AddressRegion.caribbean,
    "🇻🇨",
  ),
  ws('WS', 'WSM', 'Samoa', false, 1, AddressRegion.polynesia, "🇼🇸"),
  sm('SM', 'SMR', 'San Marino', false, 1, AddressRegion.southernEurope, "🇸🇲"),
  st(
    'ST',
    'STP',
    'Sao Tome and Principe',
    false,
    1,
    AddressRegion.middleAfrica,
    "🇸🇹",
  ),
  sa('SA', 'SAU', 'Saudi Arabia', false, 1, AddressRegion.westernAsia, "🇸🇦"),
  sn('SN', 'SEN', 'Senegal', false, 1, AddressRegion.westernAfrica, "🇸🇳"),
  rs('RS', 'SRB', 'Serbia', false, 1, AddressRegion.southernEurope, "🇷🇸"),
  sc('SC', 'SYC', 'Seychelles', false, 1, AddressRegion.easternAfrica, "🇸🇨"),
  sl(
    'SL',
    'SLE',
    'Sierra Leone',
    false,
    1,
    AddressRegion.westernAfrica,
    "🇸🇱",
  ),
  sg(
    'SG',
    'SGP',
    'Singapore',
    false,
    1,
    AddressRegion.southEasternAsia,
    "🇸🇬",
  ),
  sx(
    'SX',
    'SXM',
    'Sint Maarten (Dutch part)',
    false,
    1,
    AddressRegion.caribbean,
    "🇸🇽",
  ),
  sk('SK', 'SVK', 'Slovakia', false, 1, AddressRegion.easternEurope, "🇸🇰"),
  si('SI', 'SVN', 'Slovenia', false, 1, AddressRegion.southernEurope, "🇸🇮"),
  sb('SB', 'SLB', 'Solomon Islands', false, 1, AddressRegion.melanesia, "🇸🇧"),
  so('SO', 'SOM', 'Somalia', false, 1, AddressRegion.easternAfrica, "🇸🇴"),
  za(
    'ZA',
    'ZAF',
    'South Africa',
    false,
    1,
    AddressRegion.southernAfrica,
    "🇿🇦",
  ),
  gs(
    'GS',
    'SGS',
    'South Georgia and the South Sandwich Islands',
    false,
    1,
    AddressRegion.southAmerica,
    "🇬🇸",
  ),
  ss('SS', 'SSD', 'South Sudan', false, 1, AddressRegion.easternAfrica, "🇸🇸"),
  es('ES', 'ESP', 'Spain', false, 1, AddressRegion.southernEurope, "🇪🇸"),
  lk('LK', 'LKA', 'Sri Lanka', false, 1, AddressRegion.southernAsia, "🇱🇰"),
  sd(
    'SD',
    'SDN',
    'Sudan (the)',
    false,
    1,
    AddressRegion.northernAfrica,
    "🇸🇩",
  ),
  sr('SR', 'SUR', 'Suriname', false, 1, AddressRegion.southAmerica, "🇸🇷"),
  sj(
    'SJ',
    'SJM',
    'Svalbard and Jan Mayen',
    false,
    1,
    AddressRegion.northernEurope,
    "🇸🇯",
  ),
  se('SE', 'SWE', 'Sweden', false, 1, AddressRegion.northernEurope, "🇸🇪"),
  ch('CH', 'CHE', 'Switzerland', false, 1, AddressRegion.westernEurope, "🇨🇭"),
  sy(
    'SY',
    'SYR',
    'Syrian Arab Republic',
    false,
    1,
    AddressRegion.westernAsia,
    "🇸🇾",
  ),
  tw(
    'TW',
    'TWN',
    'Taiwan (Province of China)',
    false,
    1,
    AddressRegion.easternAsia,
    "🇹🇼",
  ),
  tj('TJ', 'TJK', 'Tajikistan', false, 1, AddressRegion.centralAsia, "🇹🇯"),
  tz(
    'TZ',
    'TZA',
    'Tanzania, United Republic of',
    false,
    1,
    AddressRegion.easternAfrica,
    "🇹🇿",
  ),
  th('TH', 'THA', 'Thailand', false, 1, AddressRegion.southEasternAsia, "🇹🇭"),
  tl(
    'TL',
    'TLS',
    'Timor-Leste',
    false,
    1,
    AddressRegion.southEasternAsia,
    "🇹🇱",
  ),
  tg('TG', 'TGO', 'Togo', false, 1, AddressRegion.westernAfrica, "🇹🇬"),
  tk('TK', 'TKL', 'Tokelau', false, 1, AddressRegion.notClassified, "🇹🇰"),
  to('TO', 'TON', 'Tonga', false, 1, AddressRegion.polynesia, "🇹🇴"),
  tt(
    'TT',
    'TTO',
    'Trinidad and Tobago',
    false,
    1,
    AddressRegion.caribbean,
    "🇹🇹",
  ),
  tn('TN', 'TUN', 'Tunisia', false, 1, AddressRegion.northernAfrica, "🇹🇳"),
  tr('TR', 'TUR', 'Turkey', false, 1, AddressRegion.westernAsia, "🇹🇷"),
  tm('TM', 'TKM', 'Turkmenistan', false, 1, AddressRegion.centralAsia, "🇹🇲"),
  tc(
    'TC',
    'TCA',
    'Turks and Caicos Islands (the)',
    false,
    1,
    AddressRegion.notClassified,
    "🇹🇨",
  ),
  tv('TV', 'TUV', 'Tuvalu', false, 1, AddressRegion.polynesia, "🇹🇻"),
  ug('UG', 'UGA', 'Uganda', false, 1, AddressRegion.easternAfrica, "🇺🇬"),
  ua('UA', 'UKR', 'Ukraine', false, 1, AddressRegion.easternEurope, "🇺🇦"),
  ae(
    'AE',
    'ARE',
    'United Arab Emirates (the)',
    false,
    1,
    AddressRegion.westernAsia,
    "🇦🇪",
  ),
  gb(
    'GB',
    'GBR',
    'United Kingdom of Great Britain and Northern Ireland (the)',
    false,
    1,
    AddressRegion.northernEurope,
    "🇬🇧",
  ),
  um(
    'UM',
    'UMI',
    'United States Minor Outlying Islands (the)',
    false,
    1,
    AddressRegion.oceania,
    "🇺🇲",
  ),
  uy('UY', 'URY', 'Uruguay', false, 1, AddressRegion.southAmerica, "🇺🇾"),
  uz('UZ', 'UZB', 'Uzbekistan', false, 1, AddressRegion.centralAsia, "🇺🇿"),
  vu('VU', 'VUT', 'Vanuatu', false, 1, AddressRegion.melanesia, "🇻🇺"),
  ve(
    'VE',
    'VEN',
    'Venezuela (Bolivarian Republic of)',
    false,
    1,
    AddressRegion.southAmerica,
    "🇻🇪",
  ),
  vn('VN', 'VNM', 'Viet Nam', false, 1, AddressRegion.southEasternAsia, "🇻🇳"),
  vg(
    'VG',
    'VGB',
    'Virgin Islands (British)',
    false,
    1,
    AddressRegion.notClassified,
    "🇻🇬",
  ),
  vi(
    'VI',
    'VIR',
    'Virgin Islands (U.S.)',
    false,
    1,
    AddressRegion.caribbean,
    "🇻🇮",
  ),
  wf('WF', 'WLF', 'Wallis and Futuna', false, 1, AddressRegion.oceania, "🇼🇫"),
  eh(
    'EH',
    'ESH',
    'Western Sahara',
    false,
    1,
    AddressRegion.westernAfrica,
    "🇪🇭",
  ),
  ye('YE', 'YEM', 'Yemen', false, 1, AddressRegion.westernAsia, "🇾🇪"),
  zm('ZM', 'ZMB', 'Zambia', false, 1, AddressRegion.easternAfrica, "🇿🇲"),
  zw('ZW', 'ZWE', 'Zimbabwe', false, 1, AddressRegion.easternAfrica, "🇿🇼");

  final String iso2;
  final String iso3;
  final String description;
  final bool hasStates;
  final int numLines;
  final AddressRegion region;
  final String flagUnicode;

  const Country(
    this.iso2,
    this.iso3,
    this.description,
    this.hasStates,
    this.numLines,
    this.region,
    this.flagUnicode,
  );
}

@JsonEnum(fieldRename: FieldRename.snake)
enum AddressRegion {
  southernAsia('Southern Asia', 'Southern Asia'),
  westernEurope('Western Europe', 'Western Europe'),
  southernEurope('Southern Europe', 'Southern Europe'),
  northernAfrica('Northern Africa', 'Northern Africa'),
  oceania('Oceania', 'Oceania'),
  middleAfrica('Middle Africa', 'Middle Africa'),
  notClassified('Not Classified', 'Not Classified'),
  caribbean('Caribbean', 'Caribbean'),
  southAmerica('South America', 'South America'),
  westernAsia('Western Asia', 'Western Asia'),
  australiaNewZealand('Australia/New Zealand', 'Australia/New Zealand'),
  easternEurope('Eastern Europe', 'Eastern Europe'),
  centralAmerica('Central America', 'Central America'),
  westernAfrica('Western Africa', 'Western Africa'),
  southernAfrica('Southern Africa', 'Southern Africa'),
  southEasternAsia('South-Eastern Asia', 'South-Eastern Asia'),
  easternAfrica('Eastern Africa', 'Eastern Africa'),
  easternAsia('Eastern Asia', 'Eastern Asia'),
  polynesia('Polynesia', 'Polynesia'),
  northernEurope('Northern Europe', 'Northern Europe'),
  melanesia('Melanesia', 'Melanesia'),
  centralAsia('Central Asia', 'Central Asia'),
  micronesia('Micronesia', 'Micronesia'),
  usWest('US West', 'US West'),
  usSouth('US South', 'US South'),
  usNorthEast('US North East', 'US North East'),
  usMidWest('US Midwest', 'US Midwest'),
  caWest('CA West', 'CA West'),
  caAtlantic('CA Atlantic', 'CA Atlantic'),
  caNorth('CA North', 'CA North'),
  caCentral('CA Central', 'CA Central');

  final String title;
  final String description;

  const AddressRegion(this.title, this.description);
}

@JsonEnum(fieldRename: FieldRename.snake)
enum AddressState {
  caab('AB', Country.ca, 'Alberta', AddressRegion.caWest),
  cabc('BC', Country.ca, 'British Columbia', AddressRegion.caWest),
  camb('MB', Country.ca, 'Manitoba', AddressRegion.caWest),
  canb('NB', Country.ca, 'New Brunswick', AddressRegion.caAtlantic),
  canl('NL', Country.ca, 'Newfoundland and Labrador', AddressRegion.caAtlantic),
  cant('NT', Country.ca, 'Northwest Territories', AddressRegion.caNorth),
  cans('NS', Country.ca, 'Nova Scotia', AddressRegion.caAtlantic),
  canu('NU', Country.ca, 'Nunavut', AddressRegion.caNorth),
  caon('ON', Country.ca, 'Ontario', AddressRegion.caCentral),
  cape('PE', Country.ca, 'Prince Edward Island', AddressRegion.caAtlantic),
  caqc('QC', Country.ca, 'Quebec', AddressRegion.caCentral),
  cask('SK', Country.ca, 'Saskatchewan', AddressRegion.caWest),
  cayk('YK', Country.ca, 'Yukon Territory', AddressRegion.caNorth),
  usak('AK', Country.us, 'Alaska', AddressRegion.usWest),
  usal('AL', Country.us, 'Alabama', AddressRegion.usSouth),
  usar('AR', Country.us, 'Arkansas', AddressRegion.usSouth),
  usaz('AZ', Country.us, 'Arizona', AddressRegion.usWest),
  usca('CA', Country.us, 'California', AddressRegion.usWest),
  usco('CO', Country.us, 'Colorado', AddressRegion.usWest),
  usct('CT', Country.us, 'Connecticut', AddressRegion.usNorthEast),
  usdc('DC', Country.us, 'District of Columbia', AddressRegion.usSouth),
  usde('DE', Country.us, 'Delaware', AddressRegion.usSouth),
  usfl('FL', Country.us, 'Florida', AddressRegion.usSouth),
  usga('GA', Country.us, 'Georgia', AddressRegion.usSouth),
  ushi('HI', Country.us, 'Hawaii', AddressRegion.usWest),
  usia('IA', Country.us, 'Iowa', AddressRegion.usMidWest),
  usid('ID', Country.us, 'Idaho', AddressRegion.usWest),
  usil('IL', Country.us, 'Illinois', AddressRegion.usMidWest),
  usin('IN', Country.us, 'Indiana', AddressRegion.usMidWest),
  usks('KS', Country.us, 'Kansas', AddressRegion.usMidWest),
  usky('KY', Country.us, 'Kentucky', AddressRegion.usSouth),
  usla('LA', Country.us, 'Louisiana', AddressRegion.usSouth),
  usma('MA', Country.us, 'Massachusetts', AddressRegion.usNorthEast),
  usmd('MD', Country.us, 'Maryland', AddressRegion.usSouth),
  usme('ME', Country.us, 'Maine', AddressRegion.usNorthEast),
  usmi('MI', Country.us, 'Michigan', AddressRegion.usMidWest),
  usmn('MN', Country.us, 'Minnesota', AddressRegion.usMidWest),
  usmo('MO', Country.us, 'Missouri', AddressRegion.usMidWest),
  usms('MS', Country.us, 'Mississippi', AddressRegion.usSouth),
  usmt('MT', Country.us, 'Montana', AddressRegion.usWest),
  usnc('NC', Country.us, 'North Carolina', AddressRegion.usSouth),
  usnd('ND', Country.us, 'North Dakota', AddressRegion.usMidWest),
  usne('NE', Country.us, 'Nebraska', AddressRegion.usMidWest),
  usnh('NH', Country.us, 'New Hampshire', AddressRegion.usNorthEast),
  usnj('NJ', Country.us, 'New Jersey', AddressRegion.usNorthEast),
  usnm('NM', Country.us, 'New Mexico', AddressRegion.usWest),
  usnv('NV', Country.us, 'Nevada', AddressRegion.usWest),
  usny('NY', Country.us, 'New York', AddressRegion.usNorthEast),
  usoh('OH', Country.us, 'Ohio', AddressRegion.usMidWest),
  usok('OK', Country.us, 'Oklahoma', AddressRegion.usSouth),
  usor('OR', Country.us, 'Oregon', AddressRegion.usWest),
  uspa('PA', Country.us, 'Pennsylvania', AddressRegion.usNorthEast),
  usri('RI', Country.us, 'Rhode Island', AddressRegion.usNorthEast),
  ussc('SC', Country.us, 'South Carolina', AddressRegion.usSouth),
  ussd('SD', Country.us, 'South Dakota', AddressRegion.usMidWest),
  ustn('TN', Country.us, 'Tennessee', AddressRegion.usSouth),
  ustx('TX', Country.us, 'Texas', AddressRegion.usSouth),
  usut('UT', Country.us, 'Utah', AddressRegion.usWest),
  usva('VA', Country.us, 'Virginia', AddressRegion.usSouth),
  usvt('VT', Country.us, 'Vermont', AddressRegion.usNorthEast),
  uswa('WA', Country.us, 'Washington', AddressRegion.usWest),
  uswi('WI', Country.us, 'Wisconsin', AddressRegion.usMidWest),
  uswv('WV', Country.us, 'West Virginia', AddressRegion.usSouth),
  uswy('WY', Country.us, 'Wyoming', AddressRegion.usWest);

  final String title;
  final Country country;
  final String description;
  final AddressRegion addressRegion;

  const AddressState(
    this.title,
    this.country,
    this.description,
    this.addressRegion,
  );
}

// @JsonEnum(fieldRename: FieldRename.snake)
// enum ServingFormat {
//   glass,
//   mug,
//   bottle,
//   can,
//   shot,
//   tumbler,
//   longGlass,
//   cocktailGlass,
//   wineGlass,
//   champagneFlute,
//   pilsnerGlass,
//   snifter,
// }

// // @JsonEnum(fieldRename: FieldRename.snake)
// // enum DrinkType { cocktail, beer, wine, spirit, bubbly, cider }

// // @JsonEnum(fieldRename: FieldRename.snake)
// // enum DrinkSize {
// //   smallGlass(125.0, 'Small', [DrinkType.wine, DrinkType.bubbly]),
// //   mediumGlass(175.0, 'Medium', [DrinkType.wine]),
// //   largeGlass(250.0, 'Large', [DrinkType.wine]),
// //   amount330ml(330.0, '33 cl', [DrinkType.beer, DrinkType.cider]),
// //   amount500ml(500.0, '50 cl', [DrinkType.beer, DrinkType.cider]),
// //   amount250ml(250.0, '25 cl', [DrinkType.beer, DrinkType.cider]),
// //   amount300ml(300.0, '30 cl', [DrinkType.beer, DrinkType.cider]),
// //   amount200ml(200.0, '20 cl', [DrinkType.beer, DrinkType.cider]),
// //   amount1l(1000.0, '1 liter', [DrinkType.beer, DrinkType.cider]),
// //   amountPint(568.0, 'UK Pint', [DrinkType.beer, DrinkType.cider]),
// //   amountHalfPint(284.0, 'UK \u00BD Pint', [DrinkType.beer, DrinkType.cider]),
// //   amount8oz(237.0, '8 oz', [DrinkType.beer, DrinkType.cider]),
// //   amount12oz(355.0, '12 oz', [DrinkType.beer, DrinkType.cider]),
// //   amount16oz(473.0, 'US Pint', [DrinkType.beer, DrinkType.cider]),
// //   amount20oz(591.0, '20 oz', [DrinkType.beer, DrinkType.cider]),
// //   amount440ml(440.0, '44 cl', [DrinkType.beer, DrinkType.cider]),
// //   oneCocktail(0.0, 'One Glass', [DrinkType.cocktail]),
// //   singleShot(50.0, 'Single', [DrinkType.spirit]),
// //   doubleShot(100.0, 'Double', [DrinkType.spirit]);

// //   final double volumeInML;
// //   final String description;
// //   final List<DrinkType> drinkTypes;

// //   const DrinkSize(this.volumeInML, this.description, this.drinkTypes);
// // }

// // @JsonEnum(fieldRename: FieldRename.snake)
// // enum DrinkCompany {
// //   alone("Alone"),
// //   friends("Friends"),
// //   family("Family"),
// //   colleagues("Colleagues"),
// //   event("Event Participants");

// //   const DrinkCompany(this.title);
// //   final String title;
// // }

// @JsonEnum(fieldRename: FieldRename.snake)
// enum DrinkLocation {
//   home("Home"),
//   bar("Bar"),
//   work("Work"),
//   club("Night Club"),
//   restaurant("Restaurant"),
//   event("Event"),
//   houseParty("House Party"),
//   travel("Travelling");

//   final String title;

//   const DrinkLocation(this.title);
// }

enum ErrorType {
  loginError("Login Error");

  final String description;
  const ErrorType(this.description);
}

enum UserType {
  public("Public", "User that doesn't belong to a company"),
  admin("Admin", "NephosX admin user"),
  corporate("Corporate", "A corporate user that belongs to a company"),
  corporateAdmin("Corporate Admin", "A corporate user that has admin rights"),
  anonymous("Anonymous User", "A user that hasn't created an account");

  final String description;
  final String title;
  const UserType(this.title, this.description);
}

enum Currency {
  usd("USD", "United States Dollar"),
  eur("EUR", "Euro"),
  gbp("GBP", "British Pound"),
  jpy("JPY", "Japanese Yen");

  final String description;
  final String title;
  const Currency(this.title, this.description);
}

@JsonEnum(fieldRename: FieldRename.snake)
enum RequestStatus {
  pending("Pending"),
  inReview("In Review"),
  accepted("Accepted"),
  rejected("Rejected"),
  withdrawn("Withdrawn");

  final String description;
  const RequestStatus(this.description);
}

@JsonEnum(fieldRename: FieldRename.snake)
enum RequestType {
  createCompany("Create Company", UserType.public, UserType.admin),
  joinCompany("Join Company", UserType.public, UserType.corporateAdmin),
  authorizeCompany(
    "Authorize Company",
    UserType.corporateAdmin,
    UserType.admin,
  );

  final String description;
  final UserType requestorType;
  final UserType approverType;

  const RequestType(this.description, this.requestorType, this.approverType);
}

enum CorporateOnboardingStatus {
  invited("Invited"),
  inProgress("In Progress"),
  submitted("Submitted"),
  underReview("Under Review"),
  needAttention("Need Attention"),
  approved("Approved"),
  rejected("Rejected");

  final String description;
  const CorporateOnboardingStatus(this.description);
}
