// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ4t64hVJSvuOsKF71q2aSLngJ06g8rmM',
    appId: '1:714731543492:web:25799ad4c1a9f453126291',
    messagingSenderId: '714731543492',
    projectId: 'nephosx-dev',
    authDomain: 'nephosx-dev.firebaseapp.com',
    storageBucket: 'nephosx-dev.firebasestorage.app',
    measurementId: 'G-NZ78BH4B9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ojfJIQRfY0KEJiv-kAsozWzcCg0fwY4',
    appId: '1:714731543492:android:bd57746927fde862126291',
    messagingSenderId: '714731543492',
    projectId: 'nephosx-dev',
    storageBucket: 'nephosx-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGElZ6vsYIuk3ZRrMEbUkdDwiqZl7lSUg',
    appId: '1:714731543492:ios:311eebe5dac53089126291',
    messagingSenderId: '714731543492',
    projectId: 'nephosx-dev',
    storageBucket: 'nephosx-dev.firebasestorage.app',
    iosBundleId: 'com.nephosx.dev',
  );
}
