// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3OAC6EjHRXJyuorkfQeh9zNv2kQMG730',
    appId: '1:963212891501:web:2672d92465a1de1f047664',
    messagingSenderId: '963212891501',
    projectId: 'celera-coach',
    authDomain: 'celera-coach.firebaseapp.com',
    storageBucket: 'celera-coach.firebasestorage.app',
    measurementId: 'G-7CHY7P66HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF0NwViJq-1oz6Aj_L7zU4MtKe-_SiHfk',
    appId: '1:963212891501:android:8023be47281e82fd047664',
    messagingSenderId: '963212891501',
    projectId: 'celera-coach',
    storageBucket: 'celera-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPC4dl9xkDFEr90Y0LAH9vq1G9JuflKs0',
    appId: '1:963212891501:ios:377fb29a2d1a3c22047664',
    messagingSenderId: '963212891501',
    projectId: 'celera-coach',
    storageBucket: 'celera-coach.firebasestorage.app',
    iosBundleId: 'dev.celera.coach',
  );
}
